### ISSUE TITLE
Armor Trims

### ISSUE THREAD

**Issue by Hipposgrumm** [FrostBreker/OneTwentyBackport-1.19.3#5]
I don't mean to make this sound like an advertisement, but I have already backported the armor trims from 1.20.

I would just like to let you know so that you can stop pulling your hair out over it.
Here is the curseforge link and source:
https://www.curseforge.com/minecraft/mc-mods/armor-trims
https://github.com/Hipposgrumm/armor-trims

**Comment by FrostBreker** [comment]
Hi! I'm currently working on the update of my mod with the armor trims. ^^

**Comment by Hipposgrumm** [comment]
It might be notable to know that the mod isn’t 100% stable and that I am working on updates to make it better.
